---
- name: Run Open WebUI
  hosts: localhost
  connection: local
  gather_facts: false
  become: false

  vars:
    open_webui_data_dir: "~/.open-webui"

  tasks:
    - name: Start Open WebUI serve command in background
      ansible.builtin.shell: |
        DATA_DIR={{ open_webui_data_dir }} nohup uvx --python 3.11 open-webui@latest serve > /dev/null 2>&1 &
      args:
        executable: /bin/bash
      changed_when: false

    - name: Wait for Open WebUI to be available on port 8080
      ansible.builtin.wait_for:
        port: 8080
        host: localhost
        timeout: 240
        state: started
