name: Test docker

on:
  push:
    paths:
      - '.github/actions/setup-docker/**'
      - 'action-setup-docker.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # we can't run docker on macos-latest. For more info read macos-docker.md
        os: [ ubuntu-latest ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test Docker
        run: docker --version
        continue-on-error: true

      - name: Setup Docker
        uses: ./.github/actions/setup-docker
        with:
          verify: 'true'

      - name: Test Docker
        run: docker --version
